-- 코드를 입력하세요
SELECT CAST(DATE_FORMAT(DATETIME, '%H') as unsigned) AS HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE CAST(DATE_FORMAT(DATETIME, '%H') as unsigned) BETWEEN 9 AND 19
GROUP BY CAST(DATE_FORMAT(DATETIME, '%H') as unsigned)
ORDER BY HOUR